name: Coverage

on: [push]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install pytest
        pip install pytest-asyncio
        pip install coveragepip 
        pip install .
    - name: Calculate coverage
      env:
        API_KEY: ${{ secrets.TRACKUNIT_API_KEY }}
      run: |
        echo $API_KEY | python -c $'import sys\nkey = sys.stdin.readline().strip()\nif len(key) == 32:\n   open("api.key","w").write(key)\nelse:\n   print("wrong length "+str(len(key)))\n   sys.exit(1)\n'
        coverage run -m --source=pytrackunit pytest -x --ignore=tests\test_real_data.py
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

